##### Apply Pipeline #######

trigger:
  - feature

pool:
  vmImage: ubuntu-latest

variables:
  rg_group: 'iaac-azure-tf-logs'
  sa_name: 'iaaclabs'
  cont_name: 'iaacazuretflogs'
  storage_key: 'terraform.tfstate'

stages:
  - stage: stage validate
    jobs:
      - job: job validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@0
          displayName: install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV3@3
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'
            backendAzureRmResourceGroupName: 'FRED'
            backendAzureRmStorageAccountName: 'iaaclabs'
            backendAzureRmContainerName: 'iaacazuretflogs'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV3@3
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
  - stage: stage deploy
    condition: succeeded('tfvalidate')
    dependsOn: validate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@0
            displayName: deptfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'
              backendAzureRmResourceGroupName: 'FRED'
              backendAzureRmStorageAccountName: 'iaaclabs'
              backendAzureRmContainerName: 'iaacazuretflogs'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV3@3
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'
          - task: TerraformTaskV3@3
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'